# .goreleaser.yml
version: 2  # ADICIONE ISSO: versão 2 é obrigatória no GoReleaser v2+

project_name: go-release-manager

# -------------------------------
# Compilação
# -------------------------------
builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: go-release-manager
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

# -------------------------------
# Arquivos (APENAS UM archive!)
# -------------------------------
archives:
  - id: release-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - config.example.*

# -------------------------------
# Checksums
# -------------------------------
checksum:
  name_template: checksums.txt
  algorithm: sha256

# -------------------------------
# Snapshots
# -------------------------------
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# -------------------------------
# Changelog
# -------------------------------
changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - 'Merge pull request'
      - 'Merge branch'