name: Release

on:
  push:
    tags:
      - 'v*' # Acionado por tags v*

permissions:
  contents: write # Necessário para criar o release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 é crucial para o GoReleaser ler o histórico para o changelog
          fetch-depth: 0
          # REMOVIDO: fetch-tags: true
          # REMOVIDO: ref: ${{ github.ref }}
          # Vamos confiar no comportamento padrão da action checkout@v4
          # quando acionada por um evento de tag.

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24 # Confirma que é a versão do teu go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # args: release --rm-dist (ou --clean, ambos funcionam)
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}